

own_path := ./

ed25519_path := ./ed25519/src/

sha_path := ./SHA/src/

root_path := ./../

all:

	cp $(ed25519_path)*.c $(sha_path)*.cpp $(root_path)
	cp $(ed25519_path)*.h $(sha_path)*.h $(root_path)